name: ctf_notebook_env
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - ipykernel
  - numpy
  - matplotlib
  - ipywidgets
  - ipympl
