name: ctf_notebook_env
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - ipykernel=6.29.5
  - numpy=2.1.3
  - matplotlib=3.9.2
  - ipywidgets=8.1.5
  - ipympl=0.9.5
